server:
  port: 10010
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: auth-service
          uri: lb://authservice
          predicates:
            - Path=/auth/**
        - id: shop-service
          uri: lb://shopservice
          predicates:
            - Path=/shop/**
        - id: money-service
          uri: lb://moneyservice
          predicates:
            - Path=/money/**
        - id: user-service # 路由标示，必须唯一
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: admin-service
          uri: lb://adminservice
          predicates:
            - Path=/admin/**
#      default-filters:
#        - AddRequestHeader=Truth,Itcast is freaking awesome!