server:
  port: 8095
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_money?useSSL=false
    username: root
    password: 1234zjx
    driver-class-name: com.mysql.cj.jdbc.Driver
  shardingsphere:
    sharding:
      default-database-strategy:
      tables:
#      discovery:
#        cluster-name: HZ
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

pattern:
  name: 本地环境local