server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_auth
    username: root
    password: 1234zjx
  application:
    name: authservice
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址
  redis:
    # redis服务器地址（默认为loaclhost）
    host: localhost
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password:
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true